export const PRODUCT_PARAMETERS_REQUEST = 'PRODUCT_PARAMETERS_REQUEST';
export const PRODUCT_PARAMETERS_SUCCESS = 'PRODUCT_PARAMETERS_SUCCESS';
export const PRODUCT_PARAMETERS_FAIL = 'PRODUCT_PARAMETERS_FAIL';